##
#  Xiaomi Redmi Note 9 Pro 5G (gauguin) - Snapdragon 750G / SM7225 / Bitra
#
#  GENERATED by tools/make_uefi_platform.py - values come from this device's
#  own XBL configuration and device tree.
#
#  SPDX-License-Identifier: BSD-2-Clause-Patent
##

[Defines]
  PLATFORM_NAME                  = gauguin
  PLATFORM_GUID                  = 7E1B4C62-2F4A-4D18-9E31-2C5A0D8B6F41
  PLATFORM_VERSION               = 0.1
  DSC_SPECIFICATION              = 0x00010005
  OUTPUT_DIRECTORY               = Build/gauguinPkg
  SUPPORTED_ARCHITECTURES        = AARCH64
  BUILD_TARGETS                  = RELEASE|DEBUG
  SKUID_IDENTIFIER               = DEFAULT
  FLASH_DEFINITION               = gauguinPkg/gauguin.fdf
  #
  # Display driver.
  #
  #   1 = Qualcomm's DisplayDxe, which knows this panel and re-initialises it
  #       from the panel XML. This is the goal, but it is also the least
  #       forgiving failure mode: a wrong timing or panel ID gives a black
  #       screen and no information at all.
  #
  #   0 = SiliciumPkg's SimpleFbDxe, which draws a text console onto the
  #       framebuffer the bootloader already set up (it locates the "Display
  #       Reserved" region - which this board's own uefiplat.cfg defines at
  #       0xA0000000). Because the bootloader has just painted the boot logo
  #       there, text lands on a live framebuffer without any panel work.
  #
  # Both lists are already in DXE.inc/APRIORI.inc behind
  # `!if $(USE_CUSTOM_DISPLAY_DRIVER) == 1`, so this one value switches the
  # whole thing. See docs/07 for why the first flash test used 0.
  #
  USE_CUSTOM_DISPLAY_DRIVER      = 0

  #
  # USB host stack.
  #
  #   1 = XhciPciEmulationDxe + XhciDxe + UsbInitDxe, so the firmware can see a
  #       USB stick. Required for P3: a Windows installer has to arrive on one.
  #       All three go into DXE.inc and none into APRIORI.inc, so the a-priori
  #       batch is the same 70 entries either way and P2's reading stays
  #       comparable between the two builds. XhciPciEmulationDxe is left to its
  #       own depex on purpose - see XHCI_HOST_DRIVERS in
  #       tools/make_uefi_platform.py for why bitra's a-priori placement of it
  #       is not copied.
  #
  #   0 = the USB host controller is not brought up. Device mode
  #       (UsbfnDwc3Dxe/UsbConfigDxe/UsbMsdDxe) still works, which is what
  #       fastboot and the device's own USB gadget use.
  #
  # The blobs are the one thing under Binaries/gauguin/ that did NOT come from
  # this phone: its XBL carries no host driver, so there is nothing to extract,
  # and the SM7225 sibling's copies are used instead. That makes this switch
  # different in kind from the display one - it is the only one that changes
  # where a driver came from. See SIBLING_BLOBS in tools/make_xbl_binaries.py.
  #
  # Off by default: nobody has seen these three run on this phone.
  #
  USE_XHCI_HOST_DRIVER           = 1

  #
  # 0 = SM7225 (Snapdragon 750G)
  #
  SOC_TYPE                       = 0

!include BitraPkg/BitraPkg.dsc.inc

[PcdsFixedAtBuild]
  #
  # DDR
  #
  gArmTokenSpaceGuid.PcdSystemMemoryBase|0x80000000

  #
  # UEFI Stack - from the "UEFI Stack" region in uefiplat.cfg
  #
  gArmPlatformTokenSpaceGuid.PcdCPUCoresStackBase|0x9FF90000
  gArmPlatformTokenSpaceGuid.PcdCPUCorePrimaryStackSize|0x40000

  #
  # SMBIOS
  #
  gSiliciumPkgTokenSpaceGuid.PcdSmbiosSystemManufacturer|"Xiaomi"
  gSiliciumPkgTokenSpaceGuid.PcdSmbiosSystemModel|"Redmi Note 9 Pro 5G"
  gSiliciumPkgTokenSpaceGuid.PcdSmbiosSystemRetailModel|"gauguin"
  gSiliciumPkgTokenSpaceGuid.PcdSmbiosSystemRetailSku|"M2007J17C"
  gSiliciumPkgTokenSpaceGuid.PcdSmbiosSystemBoardModel|"gauguin"

  #
  # Simple Frame Buffer - 1080x2400, the panel's native mode
  #
  gSiliciumPkgTokenSpaceGuid.PcdFrameBufferWidth|1080
  gSiliciumPkgTokenSpaceGuid.PcdFrameBufferHeight|2400
  gSiliciumPkgTokenSpaceGuid.PcdFrameBufferColorDepth|32

  #
  # Platform PEI
  #
  gQcomPkgTokenSpaceGuid.PcdPlatformType|"WP"

[LibraryClasses]
  #
  # Memory Libraries
  #
  MemoryMapLib|gauguinPkg/Library/MemoryMapLib/MemoryMapLib.inf

  #
  # QCOM Libraries
  #
  ConfigurationMapLib|gauguinPkg/Library/ConfigurationMapLib/ConfigurationMapLib.inf

[Components]
  #
  # ACPI Tables
  #
  # The module resolves as `gauguin/AcpiTables.inf` because
  # `Silicium-ACPI/Platforms/Xiaomi` is on PackagesPath - the same way surya's
  # resolves. The .aml files it lists are prebuilt binaries the build copies
  # into the volume, not sources it compiles; DSDT.aml is compiled from
  # tools/acpi/gauguin.asl by tools/sync-uefi-platform.sh.
  #
  gauguin/AcpiTables.inf
