#!/usr/bin/env python3
"""Generate the UEFI platform package for gauguin from Qualcomm's own config.

The two libraries a Mu-Silicium platform package has to provide are pure data:

  MemoryMapLib        the DDR and MMIO map UEFI is told about
  ConfigurationMapLib the platform tuning parameters

Both are exactly what the phone's XBL already carries in `uefiplat.cfg`, which
this project extracted into `device/config/`. So instead of hand-transcribing
~80 memory regions (and getting one wrong in a way that only shows up as a hang),
this reads Qualcomm's own numbers and emits the C.

Reference packages for the surrounding boilerplate: `MooreaPkg` (SM7150) at the
SoC level and `suryaPkg` (Xiaomi POCO X3 NFC) at the board level.

Usage:  make_uefi_platform.py [--repo DIR]
"""
import argparse
import glob
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)

sys.path.insert(0, HERE)
from make_xbl_binaries import (guid_for, present_drivers, stage_sibling_blobs,   # noqa: E402
                               SIBLING_SOURCE, SIBLING_BLOBS)

LICENSE = """/**
  Copyright (c) 2011-2012, ARM Limited. All rights reserved.
  SPDX-License-Identifier: BSD-2-Clause-Patent
**/
"""

GEN_NOTE = """/*
 * GENERATED by tools/make_uefi_platform.py - do not edit by hand.
 *
 * The data below is transcribed from this device's own XBL configuration
 * (device/config/uefiplat.cfg), recovered by tools/xbl_extract.py. It is
 * Qualcomm's description of this exact board, not an approximation.
 */
"""

# Values that carry over from the SoC family (SM7225/SM6350) rather than the
# board. GIC bases confirmed against both uefiplat.cfg and the device tree.
SOC_DEFAULTS = dict(
    gic_dist=0x17A00000,
    gic_redist=0x17A60000,
    cpu_model='"Snapdragon (TM) 750G @ 2.21 GHz"',
    cpu_part='"SM7225"',
    acpi_oem_table_id=0x202041544942,   # "BITRA  " little-endian
    acpi_oem_revision=0x7225,
)


def parse_uefiplat(path):
    """Return (memory_map, register_map, config_params) from uefiplat.cfg.

    The two map sections share one line format:
        0xADDR, 0xSIZE, "Label", HobOption, ResourceType, ResourceAttribute,
        MemoryType, ArmAttribute
    """
    memory, registers, params = [], [], []
    section = None
    for raw in open(path, encoding="utf-8", errors="replace"):
        line = raw.strip()
        if line.startswith("[") and line.endswith("]"):
            section = line.strip("[]")
            continue
        if not line or line.startswith("#"):
            continue
        if section in ("MemoryMap", "RegisterMap"):
            m = re.match(
                r'^(0x[0-9A-Fa-f]+)\s*,\s*(0x[0-9A-Fa-f]+)\s*,\s*"([^"]*)"\s*,\s*'
                r'(\w+)\s*,\s*(\w+)\s*,\s*(\w+)\s*,\s*(\w+)\s*(?:,\s*(\w+))?', line)
            if not m:
                continue
            addr, size, label, hob, rtype, rattr, mtype, armattr = m.groups()
            entry = dict(addr=int(addr, 16), size=int(size, 16), label=label,
                         hob=hob, rtype=rtype, rattr=rattr, mtype=mtype,
                         armattr=armattr or "NS_DEVICE")
            (memory if section == "MemoryMap" else registers).append(entry)
        elif section == "ConfigParameters":
            m = re.match(r'^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.+?)\s*$', line)
            if not m:
                continue
            key, val = m.groups()
            if val.startswith('"'):
                continue                      # strings are not map entries
            try:
                params.append((key, int(val, 0)))
            except ValueError:
                pass
    return memory, registers, params


def emit_memmap(memory, registers, out):
    w = out.write
    w(LICENSE)
    w('#include <Library/MemoryMapLib.h>\n\n')
    w(GEN_NOTE)
    w("STATIC\nEFI_MEMORY_REGION_DESCRIPTOR\ngMemoryDescriptor[] = {\n")
    w("  // Name, Address, Length, HobOption, ResourceType, ResourceAttribute, MemoryType, ArmAttribute\n")
    w("\n  // DDR Regions\n")
    for e in memory:
        w(f'  {{"{e["label"]}", 0x{e["addr"]:08X}, 0x{e["size"]:08X}, {e["hob"]}, '
          f'{e["rtype"]}, {e["rattr"]}, {e["mtype"]}, {e["armattr"]}}},\n')
    w("\n  // Register Regions\n")
    for e in registers:
        w(f'  {{"{e["label"]}", 0x{e["addr"]:08X}, 0x{e["size"]:08X}, {e["hob"]}, '
          f'{e["rtype"]}, {e["rattr"]}, {e["mtype"]}, {e["armattr"]}}},\n')
    w("};\n\n")
    w("""VOID
GetMemoryMap (
  OUT EFI_MEMORY_REGION_DESCRIPTOR **MemoryDescriptor,
  OUT UINT8                         *MemoryDescriptorCount)
{
  // Pass Data
  *MemoryDescriptor      = gMemoryDescriptor;
  *MemoryDescriptorCount = ARRAY_SIZE (gMemoryDescriptor);
}
""")
    return len(memory) + len(registers)


# Keys in [ConfigParameters] that are metadata or strings rather than platform
# parameters, and so must not appear in the UEFI configuration map. The string
# ones are already filtered out by the parser; these are the numeric ones that
# describe the file rather than the board.
CONFIG_META_KEYS = {
    "ConfigParameterCount",     # how many entries the vendor file has
}

# Values Mu-Silicium's ConfigMap expects that uefiplat.cfg does not spell out
# under a matching name. Kept explicit so their origin is visible.
CONFIG_EXTRA = [
    ("DetectRetailUserAttentionHotkey", 0x00),
    ("DetectRetailUserAttentionHotkeyCode", 0x17),
    ("EnableOEMSetupAppInRetail", 0x0),
    ("DDRInfoNotifyFlag", 0x1),
]


def emit_configmap(params, out):
    w = out.write
    w(LICENSE)
    w('#include <Library/ConfigurationMapLib.h>\n\n')
    w(GEN_NOTE)
    w("STATIC\nEFI_CONFIGURATION_ENTRY_DESCRIPTOR\ngConfigurationDescriptor[] = {\n")
    w("  // Configuration Map\n")
    n = 0
    for key, val in params:
        if key in CONFIG_META_KEYS:
            continue
        w(f'  {{"{key}", 0x{val:X}}},\n')
        n += 1
    w("  // added by the generator, not present verbatim in uefiplat.cfg\n")
    for key, val in CONFIG_EXTRA:
        w(f'  {{"{key}", 0x{val:X}}},\n')
        n += 1
    w("};\n\n")
    w("""VOID
GetConfigurationMap (
  OUT EFI_CONFIGURATION_ENTRY_DESCRIPTOR **ConfigurationDescriptor,
  OUT UINT8                               *ConfigurationDescriptorCount)
{
  // Pass Data
  *ConfigurationDescriptor      = gConfigurationDescriptor;
  *ConfigurationDescriptorCount = ARRAY_SIZE (gConfigurationDescriptor);
}
""")
    return n


BITRA_DSC_INC = """##
#  Bitra platform (Snapdragon 750G / SM7225) - generated for gauguin.
#  SPDX-License-Identifier: BSD-2-Clause-Patent
##

[Defines]
  #
  # Timer
  #
  USE_PHYSICAL_TIMER                         = 1

  #
  # KEP
  #
  HAS_ACTLR_EL1_UNIMPLEMENTED_ERRATA         = 0
  HAS_AMCNTENSET0_EL0_UNIMPLEMENTED_ERRATA   = 0
  HAS_GIC_V3_WITHOUT_IRM_FLAG_SUPPORT_ERRATA = 0
  HAS_PSCI_MEMPROTECT_FAILING_ERRATA         = 1

!include QcomPkg/QcomPkg.dsc.inc

[BuildOptions]
  #
  # Cortex-A77 + Cortex-A55. The Kryo 570 cores implement ARMv8.2-A.
  #
  *_*_AARCH64_CC_FLAGS = -march=armv8.2-a+crypto+rcpc

[PcdsFixedAtBuild]
  #
  # ACPI
  #
  gEfiMdeModulePkgTokenSpaceGuid.PcdAcpiDefaultOemTableId|0x{acpi_oem_table_id:X}
  gEfiMdeModulePkgTokenSpaceGuid.PcdAcpiDefaultOemRevision|0x{acpi_oem_revision:X}

  #
  # CPU - 2x A77 + 6x A55
  #
  gArmPlatformTokenSpaceGuid.PcdCoreCount|8
  gArmPlatformTokenSpaceGuid.PcdClusterCount|2

  #
  # GIC. Bases agree between uefiplat.cfg and the device tree; uefiplat.cfg
  # calls the distributor GIC600, upstream calls it GIC500 - same address.
  #
  gArmTokenSpaceGuid.PcdGicDistributorBase|0x{gic_dist:X}
  gArmTokenSpaceGuid.PcdGicRedistributorsBase|0x{gic_redist:X}

  #
  # Timer
  #
  gArmTokenSpaceGuid.PcdArmArchTimerSecIntrNum|17
  gArmTokenSpaceGuid.PcdArmArchTimerIntrNum|18

  #
  # Shared RFS Area
  #
  gQcomPkgTokenSpaceGuid.PcdDestinationVmCount|2

  #
  # SMBIOS
  #
  gSiliciumPkgTokenSpaceGuid.PcdSmbiosProcessorModel|{cpu_model}
  gSiliciumPkgTokenSpaceGuid.PcdSmbiosProcessorPartNumber|{cpu_part}

[LibraryClasses]
  #
  # SEC Libraries
  #
  PlatformSecLib|BitraPkg/Library/PlatformSecLib/PlatformSecLib.inf

  #
  # ACPI Libraries
  #
  AcpiTableUpdateLib|BitraPkg/Library/AcpiTableUpdateLib/AcpiTableUpdateLib.inf
"""

GAUGUIN_DSC = """##
#  Xiaomi Redmi Note 9 Pro 5G (gauguin) - Snapdragon 750G / SM7225 / Bitra
#
#  GENERATED by tools/make_uefi_platform.py - values come from this device's
#  own XBL configuration and device tree.
#
#  SPDX-License-Identifier: BSD-2-Clause-Patent
##

[Defines]
  PLATFORM_NAME                  = gauguin
  PLATFORM_GUID                  = 7E1B4C62-2F4A-4D18-9E31-2C5A0D8B6F41
  PLATFORM_VERSION               = 0.1
  DSC_SPECIFICATION              = 0x00010005
  OUTPUT_DIRECTORY               = Build/gauguinPkg
  SUPPORTED_ARCHITECTURES        = AARCH64
  BUILD_TARGETS                  = RELEASE|DEBUG
  SKUID_IDENTIFIER               = DEFAULT
  FLASH_DEFINITION               = gauguinPkg/gauguin.fdf
  #
  # Display driver.
  #
  #   1 = Qualcomm's DisplayDxe, which knows this panel and re-initialises it
  #       from the panel XML. This is the goal, but it is also the least
  #       forgiving failure mode: a wrong timing or panel ID gives a black
  #       screen and no information at all.
  #
  #   0 = SiliciumPkg's SimpleFbDxe, which draws a text console onto the
  #       framebuffer the bootloader already set up (it locates the "Display
  #       Reserved" region - which this board's own uefiplat.cfg defines at
  #       0xA0000000). Because the bootloader has just painted the boot logo
  #       there, text lands on a live framebuffer without any panel work.
  #
  # Both lists are already in DXE.inc/APRIORI.inc behind
  # `!if $(USE_CUSTOM_DISPLAY_DRIVER) == 1`, so this one value switches the
  # whole thing. See docs/07 for why the first flash test used 0.
  #
  USE_CUSTOM_DISPLAY_DRIVER      = {display}

  #
  # USB host stack.
  #
  #   1 = XhciPciEmulationDxe + XhciDxe + UsbInitDxe, so the firmware can see a
  #       USB stick. Required for P3: a Windows installer has to arrive on one.
  #       All three go into DXE.inc and none into APRIORI.inc, so the a-priori
  #       batch is the same 70 entries either way and P2's reading stays
  #       comparable between the two builds. XhciPciEmulationDxe is left to its
  #       own depex on purpose - see XHCI_HOST_DRIVERS in
  #       tools/make_uefi_platform.py for why bitra's a-priori placement of it
  #       is not copied.
  #
  #   0 = the USB host controller is not brought up. Device mode
  #       (UsbfnDwc3Dxe/UsbConfigDxe/UsbMsdDxe) still works, which is what
  #       fastboot and the device's own USB gadget use.
  #
  # The blobs are the one thing under Binaries/gauguin/ that did NOT come from
  # this phone: its XBL carries no host driver, so there is nothing to extract,
  # and the SM7225 sibling's copies are used instead. That makes this switch
  # different in kind from the display one - it is the only one that changes
  # where a driver came from. See SIBLING_BLOBS in tools/make_xbl_binaries.py.
  #
  # Off by default: nobody has seen these three run on this phone.
  #
  USE_XHCI_HOST_DRIVER           = {xhci_host}

  #
  # 0 = SM7225 (Snapdragon 750G)
  #
  SOC_TYPE                       = 0

!include BitraPkg/BitraPkg.dsc.inc

[PcdsFixedAtBuild]
  #
  # DDR
  #
  gArmTokenSpaceGuid.PcdSystemMemoryBase|0x80000000

  #
  # UEFI Stack - from the "UEFI Stack" region in uefiplat.cfg
  #
  gArmPlatformTokenSpaceGuid.PcdCPUCoresStackBase|0x9FF90000
  gArmPlatformTokenSpaceGuid.PcdCPUCorePrimaryStackSize|0x40000

  #
  # SMBIOS
  #
  gSiliciumPkgTokenSpaceGuid.PcdSmbiosSystemManufacturer|"Xiaomi"
  gSiliciumPkgTokenSpaceGuid.PcdSmbiosSystemModel|"Redmi Note 9 Pro 5G"
  gSiliciumPkgTokenSpaceGuid.PcdSmbiosSystemRetailModel|"gauguin"
  gSiliciumPkgTokenSpaceGuid.PcdSmbiosSystemRetailSku|"M2007J17C"
  gSiliciumPkgTokenSpaceGuid.PcdSmbiosSystemBoardModel|"gauguin"

  #
  # Simple Frame Buffer - 1080x2400, the panel's native mode
  #
  gSiliciumPkgTokenSpaceGuid.PcdFrameBufferWidth|1080
  gSiliciumPkgTokenSpaceGuid.PcdFrameBufferHeight|2400
  gSiliciumPkgTokenSpaceGuid.PcdFrameBufferColorDepth|32

  #
  # Platform PEI
  #
  gQcomPkgTokenSpaceGuid.PcdPlatformType|"WP"

[LibraryClasses]
  #
  # Memory Libraries
  #
  MemoryMapLib|gauguinPkg/Library/MemoryMapLib/MemoryMapLib.inf

  #
  # QCOM Libraries
  #
  ConfigurationMapLib|gauguinPkg/Library/ConfigurationMapLib/ConfigurationMapLib.inf

[Components]
  #
  # ACPI Tables
  #
  # The module resolves as `gauguin/AcpiTables.inf` because
  # `Silicium-ACPI/Platforms/Xiaomi` is on PackagesPath - the same way surya's
  # resolves. The .aml files it lists are prebuilt binaries the build copies
  # into the volume, not sources it compiles; DSDT.aml is compiled from
  # tools/acpi/gauguin.asl by tools/sync-uefi-platform.sh.
  #
  gauguin/AcpiTables.inf
"""

GAUGUIN_FDF = """##
#  Xiaomi Redmi Note 9 Pro 5G (gauguin)
#  SPDX-License-Identifier: BSD-2-Clause-Patent
##

[FD.SILICIUM_UEFI]
BaseAddress   = $(FD_BASE)|gArmTokenSpaceGuid.PcdFdBaseAddress
Size          = $(FD_SIZE)|gArmTokenSpaceGuid.PcdFdSize
ErasePolarity = 1

# BlockSize * NumBlocks = Size
BlockSize     = 0x1000
NumBlocks     = $(FD_BLOCKS)

0x00000000|$(FD_SIZE)
gArmTokenSpaceGuid.PcdFvBaseAddress|gArmTokenSpaceGuid.PcdFvSize
FV = FVMAIN_COMPACT

[FV.FvMain]
FvNameGuid         = CD8D4C84-20AD-4073-8A28-3400FAE05941
BlockSize          = 0x1000
NumBlocks          = 0
FvAlignment        = 8
ERASE_POLARITY     = 1
MEMORY_MAPPED      = TRUE
STICKY_WRITE       = TRUE
LOCK_CAP           = TRUE
LOCK_STATUS        = TRUE
WRITE_DISABLED_CAP = TRUE
WRITE_ENABLED_CAP  = TRUE
WRITE_STATUS       = TRUE
WRITE_LOCK_CAP     = TRUE
WRITE_LOCK_STATUS  = TRUE
READ_DISABLED_CAP  = TRUE
READ_ENABLED_CAP   = TRUE
READ_STATUS        = TRUE
READ_LOCK_CAP      = TRUE
READ_LOCK_STATUS   = TRUE

  !include Include/APRIORI.inc
  !include Include/DXE.inc
  !include Include/RAW.inc

  # RAM Manager
  INF SiliciumPkg/Drivers/RamManagerDxe/RamManagerDxe.inf

  # SmBios
  INF MdeModulePkg/Universal/SmbiosDxe/SmbiosDxe.inf
  INF SiliciumPkg/Drivers/SmBiosTableDxe/SmBiosTableDxe.inf

  #
  # NOTE: BootManagerMenuApp is NOT listed here, and must not be.
  #
  # It already reaches the firmware volume through the DSC chain, and listing it
  # again fails the build with the 111th and 117th files sharing GUID
  # EEC25BDC-67F2-4D95-B1D5-F81B2039D11D. Which is the useful part: it means
  # BdsDxe's PcdBootManagerMenuFile fallback does resolve, so a device with no
  # OS installed has something it can put on the screen - SiliciumPkg's boot
  # manager draws "[Volume Up] Boot Manager" on the console during its timeout,
  # and this is the menu that message promises. On a phone with no UART that is
  # the difference between a working firmware and a dead one.
  #

  # ACPI
  INF MdeModulePkg/Universal/Acpi/AcpiTableDxe/AcpiTableDxe.inf
  INF MdeModulePkg/Universal/Acpi/AcpiPlatformDxe/AcpiPlatformDxe.inf
  #
  # The tables themselves. `RuleOverride = ACPITABLE` is
  # Silicon/Silicium/SiliciumPkg/Common.fdf.inc's rule and it puts each entry
  # into the FV as a RAW section, which is what the AcpiTableDxe above scans
  # the volume for.
  #
  INF RuleOverride = ACPITABLE gauguin/AcpiTables.inf

  !include QcomPkg/Extra.fdf.inc

[FV.FVMAIN_COMPACT]
FvAlignment        = 8
ERASE_POLARITY     = 1
MEMORY_MAPPED      = TRUE
STICKY_WRITE       = TRUE
LOCK_CAP           = TRUE
LOCK_STATUS        = TRUE
WRITE_DISABLED_CAP = TRUE
WRITE_ENABLED_CAP  = TRUE
WRITE_STATUS       = TRUE
WRITE_LOCK_CAP     = TRUE
WRITE_LOCK_STATUS  = TRUE
READ_DISABLED_CAP  = TRUE
READ_ENABLED_CAP   = TRUE
READ_STATUS        = TRUE
READ_LOCK_CAP      = TRUE
READ_LOCK_STATUS   = TRUE

  INF SiliciumPkg/Sec/Sec.inf

  FILE FV_IMAGE = 9E21FD93-9C72-4c15-8C4B-E77F1DB2D792 {
    SECTION GUIDED EE4E5898-3914-4259-9D6E-DC7BD79403CF PROCESSING_REQUIRED = TRUE {
      SECTION FV_IMAGE = FVMAIN
    }
  }

  !include SiliciumPkg/Common.fdf.inc
"""

GAUGUIN_DEC = """##
#  Xiaomi Redmi Note 9 Pro 5G (gauguin)
#  SPDX-License-Identifier: BSD-2-Clause-Patent
##

[Defines]
  DEC_SPECIFICATION = 0x00010005
  PACKAGE_NAME      = gauguinPkg
  PACKAGE_GUID      = 7E1B4C62-2F4A-4D18-9E31-2C5A0D8B6F42
  PACKAGE_VERSION   = 0.1
"""

GAUGUIN_ACPI_INF = """##
#  Xiaomi Redmi Note 9 Pro 5G (gauguin) - ACPI tables
#  SPDX-License-Identifier: BSD-2-Clause-Patent
##
#
# The DSDT is ours (tools/acpi/gauguin.asl, compiled to DSDT.aml here). The
# other four come from Silicon/Qualcomm/Moorea unmodified, because everything
# they carry is SoC geometry and all of it was checked against this board's own
# device tree - see docs/07-uefi-platform.md, "which SoC's ACPI tables gauguin
# can use". Moorea's other six are deliberately not here: MCFG describes PCIe
# and this board's device tree has no pcie node, and IORT/PPTT/CSRT/DBG2 are
# device inventories that would each have to be re-derived before they could be
# trusted. The set is Platforms/Lenovo/j706f's, plus FACS, which is generic.
#
# SSDT.aml is the shared Common/ one every platform in the tree uses.

[Defines]
  INF_VERSION                    = 0x00010005
  BASE_NAME                      = AcpiTables
  FILE_GUID                      = 7E374E25-8E01-4FEE-87F2-390C23C606CD
  MODULE_TYPE                    = USER_DEFINED
  VERSION_STRING                 = 1.0

[Binaries]
  ASL|DSDT.aml
  ASL|Common/SSDT.aml
  ASL|Moorea/APIC.aml
  ASL|Moorea/FACP.aml
  ASL|Moorea/FACS.aml
  ASL|Moorea/GTDT.aml
"""

GAUGUIN_TOML = """#
# Boot Shim Configs
#
[boot_shim]
requires_kernel_header = true

#
# UEFI FD Configs - the "UEFI FD" region from uefiplat.cfg
#
[uefi_fd]
base = 0x9FC00000
size = 0x300000

#
# Android Boot Image Kernel Configs
#
# append_dtb is off because at header_version 2 the DTB is a region of its own
# and not part of the kernel blob. Gluing it onto the kernel instead - which is
# what append_dtb does - leaves dtb_size 0 and the region empty, and ABL's
# GetSocDtb() then scans from DtbOffset to the end of the image, finds no tree,
# and returns NULL ("No match found for Soc Dtb type").
[boot_image_kernel]
kernel_compression = "gzip"
append_dtb         = false

#
# Android Boot Image Configs
#
# header_version 2, which is what this phone's own boot partition declares.
#
# This was 1. v1 is not unconditionally fatal - a v1 image whose kernel is a gzip
# package finds its tree, because on that path it is ABL's own decompressor that
# writes DtbOffset (docs/07) - but it is still wrong here, and wrong in the way
# that makes the failure hard to read. DTBImgCheckAndAppendDT computes an offset
# of its own only `if (HeaderVersion > BOOT_HEADER_VERSION_ONE)`
# (QcomModulePkg/Library/BootLib/BootLinux.c:454, and BOOT_HEADER_VERSION_ONE is
# 1); ABL's own words at :1239 are "DT size doesn't apply to header versions 0 and
# 1". So at v1 *where the tree is found* stops being a property of the header and
# becomes a property of the compression, which is not something anyone would
# guess: a raw kernel leaves DtbOffset at the 0 the BootParamlist was initialised
# with, GetSocDtb() returns NULL on its first check (`if (!DtbOffset)`,
# LocateDeviceTree.c:1005) with "DTB offset is NULL", and the appended tree is
# never reached at all.
#
# Changing it here does not make this builder's output bootable, and that is not
# something a config value can fix: build_uefi.py never passes --pagesize to
# mkbootimg, so every image it makes is page 2048 while this device's ABL and its
# stock boot both use 0x1000, and it has no way to declare a DTB region at all
# (it only ever appends one). The payload of record is built by
# tools/build-p2-payloads.sh, which wraps the same volume with
# tools/make_boot_image.py --profile stock. Setting v2 here is so that a stray
# `./build_uefi.py -d gauguin` fails for a reason that is true.
[boot_image]
header_version = 2
"""


# ---------------------------------------------------------------------------
# The three !include files the FDF pulls in.
#
# DXE.inc / APRIORI.inc list the drivers that go into the firmware volume, in
# load order. Almost every one of them is a Qualcomm binary that we extracted
# from this phone's own XBL, so the lists are the same ones the sibling board
# packages use - taken from the reference platform and rewritten to point at
# `Binaries/gauguin/`, then filtered down to the drivers we actually have.
#
# The filter is the important part: shipping an INF for a driver whose .efi is
# missing fails the FDF at build time, and shipping a driver we do not have a
# blob for would silently give us a firmware volume that does not match the
# hardware.

REF_PLATFORM = "surya"          # Xiaomi POCO X3 NFC / SM7150 - closest sibling

# APRIORI.inc is a load-order list, not just a list. CoreFwVolEventProtocolNotify
# walks the volume's Apriori file in index order and appends every match to the
# scheduled queue, and the dispatcher drains that queue first-in-first-out, so the
# position of a line here is the order in which the driver's entry point runs
# (docs/08 step 4.9). That is what makes `--apriori-move` an experiment rather
# than a cosmetic edit, and the reason a reordering is worth trying before
# anything is removed: the eight architectural-protocol providers this board never
# gets are all late in the list, which is consistent both with "these drivers
# fail" and with "something earlier in the batch fails them".

# Drivers this XBL carries that the surya reference package does not list, but
# which 16-51 other platform packages in the tree do. surya is an older SoC
# generation; the older ordering omits them. Taken from Xiaomi's aliothPkg
# (SM8250) instead, and inserted at the same anchor line alioth puts them after,
# so the relative load order is the reference's, not this generator's invention.
#
# PILDxe/PILProxyDxe are deliberately NOT inserted: the reference has PILDxe
# commented out, and they exist to load ADSP/CDSP firmware, which nothing in a
# Windows boot path consumes.
EXTRA_DRIVERS = {
    "DXE.inc": [
        ("Drivers/CmdDbDxe/CmdDbDxe.inf",       "PwrUtilsDxe"),
        ("Drivers/ClockDxe/ClockDxe.inf",       "VcsDxe"),
        ("Drivers/TLMMDxe/TLMMDxe.inf",         "FeatureEnablerDxe"),
        ("Drivers/CipherDxe/CipherDxe.inf",     "MacDxe"),
    ],
    "APRIORI.inc": [
        ("Drivers/CmdDbDxe/CmdDbDxe.inf",       "PwrUtilsDxe"),
        ("Drivers/PdcDxe/PdcDxe.inf",           "VcsDxe"),
        ("Universal/Variable/RuntimeDxe/VariableRuntimeDxe.inf", "FeatureEnablerDxe"),
        ("Drivers/CipherDxe/CipherDxe.inf",     "MacDxe"),
    ],
}

# Driver name -> path under Binaries/<device>/, for the EXTRA_DRIVERS entries.
EXTRA_PATHS = {
    "PwrUtilsDxe":      "QcomPkg/Drivers/PwrUtilsDxe/PwrUtilsDxe.inf",
    "VcsDxe":           "QcomPkg/Drivers/VcsDxe/VcsDxe.inf",
    "FeatureEnablerDxe": "QcomPkg/Drivers/FeatureEnablerDxe/FeatureEnablerDxe.inf",
    "MacDxe":           "QcomPkg/Drivers/MacDxe/MacDxe.inf",
}

# The USB *host* stack, which this phone's XBL does not carry at all and the
# surya reference therefore does not list either. See SIBLING_BLOBS in
# tools/make_xbl_binaries.py for where the three blobs come from and why - the
# short version is that Bitra is this SoC, so the SM7225 sibling's copies are
# the ones built for this hardware.
#
# Off unless `--xhci-host` is given, for the same reason the Qualcomm display
# driver is behind a switch: it is a driver nobody has yet seen run on this
# phone.
#
# DXE.inc only, and that is a deliberate departure from the sibling. bitra lists
# XhciPciEmulationDxe and XhciDxe in APRIORI.inc as well, and copying that would
# throw away the one thing that makes these files different from the other 55
# blobs: their depex. `Dispatcher.c:2111` promotes an a-priori member by setting
# `DriverEntry->Dependent = FALSE` and queueing it outright - the DEBUG line
# eleven lines below it prints `RESULT = TRUE (Apriori)` for that reason - so a
# driver in that list has its depex read and then ignored. XhciPciEmulationDxe's
# depex is a conjunction of thirteen architectural protocols, and placing it in
# the batch that runs *before* those protocols exist would ask it to start at
# the one moment it cannot. Left in DXE.inc the ordinary dependency sweep starts
# it when its protocols appear, which is also when a USB stick is worth looking
# for - the point at which BDS would go looking for a boot device anyway.
# UsbInitDxe is in DXE.inc only in bitra too, and for the same reason it is here.
#
# The consequence to keep in mind: while the eight arch providers still fail
# (docs/08 step 4.9), `EFI_BDS_ARCH_PROTOCOL` is one of them and the USB host
# stack therefore stays unstarted rather than failing. That is this file waiting
# on P2, not a second fault, and P2 SEQ will show it as absent from the batch
# rather than as a new 'L' - the array stays at 70 entries, which keeps the
# instrument comparable with the payload now in `boot`.
#
# The placement inside DXE.inc is bitra's and it does matter there.
# XhciPciEmulationDxe publishes the controller's window, XhciDxe is a
# UEFI_DRIVER that binds to the device that appears in it, and UsbBusDxe -
# already in the list, a few lines below - sits on top of both. So the pair goes
# immediately after UsbfnDwc3Dxe and immediately before the blank line that
# precedes UsbBusDxe, which is where Platforms/Realme/bitraPkg puts it.
#
# Each entry is (anchor line, paths to insert after it), wrapped in the guard
# below so one DSC value switches the whole block.
XHCI_HOST_DRIVERS = {
    "DXE.inc": [
        ("Drivers/UsbfnDwc3Dxe/UsbfnDwc3Dxe.inf", [
            "QcomPkg/Drivers/XhciPciEmulationDxe/XhciPciEmulationDxe.inf",
            "QcomPkg/Drivers/XhciDxe/XhciDxe.inf",
        ]),
        ("Drivers/UsbConfigDxe/UsbConfigDxe.inf", [
            "QcomPkg/Drivers/UsbInitDxe/UsbInitDxe.inf",
        ]),
    ],
}

XHCI_HOST_GUARD = "USE_XHCI_HOST_DRIVER"


def load_guid_table(mu_root):
    """Map RAW file name -> FILE FREEFORM GUID, from the whole Mu-Silicium tree.

    Qualcomm's panel and config files have fixed firmware-file GUIDs that every
    platform package in the tree reuses verbatim (verified: `uefipil.cfg` is
    21E9BDD9-... in surya, cepheus, vayu and marble alike). Reading them out of
    the tree beats inventing our own, because Qualcomm's own signed drivers are
    what look these files up.
    """
    table = {}
    for inc in glob.glob(os.path.join(mu_root, "Platforms/*/*/Include/RAW.inc")):
        text = open(inc, encoding="utf-8", errors="replace").read()
        for m in re.finditer(r'FILE FREEFORM = ([0-9A-Fa-f-]{36})\s*\{(.*?)\n\s*\}',
                             text, re.S):
            ui = re.search(r'SECTION UI = "([^"]+)"', m.group(2))
            if ui:
                table.setdefault(ui.group(1), m.group(1).upper())
    return table


def apply_apriori_moves(lines, moves):
    """Move the named INF lines of APRIORI.inc to just after an anchor line.

    `moves` is a list of (anchor, [name, ...]); anchor and names are substrings
    of `INF ...` lines. Nothing is added or removed, only reordered, so the
    firmware volume keeps the same files at the same offsets and the only byte
    that changes is the Apriori GUID array itself.

    Every name has to match exactly one line. A name that matches none would
    otherwise move nothing and read, in a build log, exactly like an experiment
    that ran; a name that matches two would silently move whichever came first.
    Both are exit conditions rather than warnings.

    Returns [(anchor, path), ...] for the report and for the generated header.
    """
    report = []
    for anchor, names in moves:
        anchor_at = [i for i, l in enumerate(lines)
                     if anchor in l and l.strip().startswith("INF")]
        if len(anchor_at) != 1:
            sys.exit(f"--apriori-move: anchor {anchor!r} matches "
                     f"{len(anchor_at)} INF lines in APRIORI.inc, want 1")
        src = []
        for name in names:
            at = [i for i, l in enumerate(lines)
                  if name in l and l.strip().startswith("INF")]
            if len(at) != 1:
                sys.exit(f"--apriori-move: {name!r} matches {len(at)} INF lines "
                         f"in APRIORI.inc, want 1")
            if at[0] == anchor_at[0]:
                sys.exit(f"--apriori-move: {name!r} is the anchor line {anchor!r}")
            src.append(at[0])
        if len(set(src)) != len(src):
            sys.exit(f"--apriori-move: two names under anchor {anchor!r} match "
                     f"the same line")

        picked = [lines[i] for i in src]
        # Where the anchor ends up once the moved lines are gone from in front of
        # it. Removing and re-inserting in one pass would need the indices
        # rewritten anyway, so they are rewritten once, here.
        after = anchor_at[0] - len([i for i in src if i < anchor_at[0]])
        for i in sorted(src, reverse=True):
            del lines[i]
        for offset, line in enumerate(picked):
            lines.insert(after + 1 + offset, line)
            report.append((anchor, line.strip().removeprefix("INF ")))
    return report


def rewrite_incs(ref_dir, have, device, apriori_moves=(), xhci_host=False,
                 apriori_extras=False):
    """Produce (dxe_inc, apriori_inc) for `device` from the reference package.

    `have` is the set of `QcomPkg/Drivers/.../*.inf` paths present under
    Binaries/<device>. Reference lines we cannot satisfy are commented out
    rather than dropped, so the gap stays visible in the generated file.

    `apriori_moves` reorders APRIORI.inc only, and only when asked for; the
    default output is byte-for-byte the reference order.

    `apriori_extras` promotes the EXTRA_DRIVERS of APRIORI.inc. Off by default
    because it is a dispatch-order change rather than a packaging one - see the
    note above the insertion loop, and docs/08 step 4.171.

    `xhci_host` adds the USB host stack (see XHCI_HOST_DRIVERS). Off by default,
    which is also what keeps a regeneration of an existing tree byte-identical.

    `referenced` is per file, and that is a correction rather than a style. It
    used to be one set shared by both passes, which made every
    `EXTRA_DRIVERS["APRIORI.inc"]` row dead code for a driver its `DXE.inc` twin
    had already inserted: the DXE.inc pass added the path to the shared set, and
    the APRIORI.inc pass then skipped it on `path in referenced` - silently,
    because that branch is a bare `continue` and not a `dropped` entry, so the
    generated file said nothing about it either. All four rows - `PwrUtilsDxe`,
    `VcsDxe`, `FeatureEnablerDxe` and `MacDxe` - were inserted into `DXE.inc`
    and none into `APRIORI.inc`. `out["referenced"]`, which is the union the
    orphan report at the end of the generator reads, is the one place the two
    passes' sets still belong together. See docs/08 step 4.171.
    """
    out = {}
    all_referenced = set()
    for name, key in (("DXE.inc", "dxe_inc"), ("APRIORI.inc", "apriori_inc")):
        referenced = set()
        src = os.path.join(ref_dir, "Include", name)
        text = open(src, encoding="utf-8", errors="replace").read()
        text = text.replace(f"Binaries/{REF_PLATFORM}/", f"Binaries/{device}/")

        lines, dropped, withheld = [], [], []
        for line in text.splitlines():
            m = re.match(r'^(\s*)INF Binaries/(\S+)', line)
            # `have` is keyed the way present_drivers() builds it - relative to
            # Binaries/<device>/ - so strip the device component the rename
            # above introduced before comparing.
            rel = m.group(2).split("/", 1)[1] if m and "/" in m.group(2) else None
            if m and rel not in have:
                dropped.append(m.group(2))
                lines.append(f"# dropped, no blob extracted from this XBL: {m.group(2)}")
                continue
            if m:
                referenced.add(rel)
            lines.append(line)

        # Insert the drivers surya's generation predates, at their alioth anchors.
        #
        # The APRIORI.inc half is behind `apriori_extras`, and deliberately so:
        # this is the one place where the generator's table asks for a change of
        # *dispatch order* rather than for a file to be present, and the stock
        # firmware is the authority on it (its own 74-entry array promotes
        # PwrUtilsDxe, VcsDxe and FeatureEnablerDxe and not MacDxe; see docs/08
        # step 4.171). Off by default, so a plain regeneration is byte-identical
        # to what the tree already holds and the running P2 experiment keeps the
        # a-priori array shape its instrument reads.
        for anchor, extra in EXTRA_DRIVERS.get(name, []):
            path = EXTRA_PATHS[extra]
            if path not in have or path in referenced:
                continue
            if name == "APRIORI.inc" and not apriori_extras:
                withheld.append((anchor, path))
                continue
            idx = next((i for i, l in enumerate(lines) if anchor in l), None)
            if idx is None:
                dropped.append(f"{path}  (no anchor line for {anchor})")
                continue
            lines.insert(idx + 1, f"  INF Binaries/{device}/{path}")
            referenced.add(path)

        # The USB host stack, in a conditional rather than inserted outright, so
        # the switch lives in the DSC next to USE_CUSTOM_DISPLAY_DRIVER and the
        # default build cannot acquire it by regenerating.
        uhci, xhci_dropped = [], []
        if xhci_host:
            for anchor, paths in XHCI_HOST_DRIVERS.get(name, []):
                present = [p for p in paths if p in have]
                if not present:
                    missing = f"{paths[0]}  (no blob staged for it)"
                    dropped.append(missing)
                    xhci_dropped.append(missing)
                    continue
                idx = next((i for i, l in enumerate(lines) if anchor in l), None)
                if idx is None:
                    anchorless = f"{present[0]}  (no anchor line for {anchor})"
                    dropped.append(anchorless)
                    xhci_dropped.append(anchorless)
                    continue
                lines[idx + 1:idx + 1] = (
                    [f"!if $({XHCI_HOST_GUARD}) == 1"]
                    + [f"  INF Binaries/{device}/{p}" for p in present]
                    + ["!endif"])
                referenced.update(present)
                uhci += present

        # Reordering is APRIORI.inc's alone. DXE.inc decides which FFS files the
        # volume carries and where they land, and reordering it would move every
        # offset in the map that tools/fv-inventory.py checks against.
        moved = []
        if name == "APRIORI.inc" and apriori_moves:
            moved = apply_apriori_moves(lines, apriori_moves)

        # Nothing in the reference lists these, so they would be packaged and
        # then silently left out of the firmware volume. Naming them in the file
        # keeps that visible after the generator's stdout is long gone.
        skipped = sorted(have - referenced - set(out.get("orphans_seen", set())))

        header = (f"##\n"
                  f"#  GENERATED by tools/make_uefi_platform.py from the\n"
                  f"#  {REF_PLATFORM}Pkg reference package - do not edit by hand.\n"
                  f"#\n"
                  f"#  Rewritten to Binaries/{device}/ and filtered to the drivers this\n"
                  f"#  project actually extracted from the device's own XBL.\n")
        if moved:
            header += ("#\n"
                       "#  EXPERIMENT - NOT the reference order. --apriori-move was used,\n"
                       "#  so the a-priori batch runs in the order below, not surya's:\n")
            header += "".join(f"#    {path}\n#      moved to just after {anchor}\n"
                              for anchor, path in moved)
            header += ("#  Regenerate without --apriori-move to restore the reference\n"
                       "#  order. Which one the device ran is recorded by\n"
                       "#  tools/build-apriori-variant.sh.\n")
        if uhci:
            header += ("#\n"
                       "#  --xhci-host: this file also carries the USB host stack, in\n"
                       f"#  `!if $({XHCI_HOST_GUARD}) == 1` above. Those blobs are the\n"
                       f"#  ONE exception to the sentence above - they came from\n"
                       f"#  Binaries/{SIBLING_SOURCE}/, not from this device, because this\n"
                       "#  device's XBL has no host-controller driver to extract. See\n"
                       "#  SIBLING_BLOBS in tools/make_xbl_binaries.py.\n")
            header += "".join(f"#    {p}\n" for p in uhci)
        if dropped:
            header += "#\n#  Not available (commented out below):\n"
            header += "".join(f"#    {d}\n" for d in sorted(set(dropped)))
        if withheld:
            header += ("#\n"
                       "#  Packaged and in DXE.inc, but NOT promoted here: the alioth\n"
                       "#  reference puts each of these into the a-priori batch and the\n"
                       "#  stock firmware's own array agrees (see docs/08 step 4.171 for\n"
                       "#  which of them it agrees about). Promotion is a dispatch-order\n"
                       "#  change, so it is a switch rather than a default: rerun the\n"
                       "#  generator with --apriori-extras to get these lines here.\n")
            header += "".join(f"#    {p}\n#      would go just after {a}\n"
                              for a, p in withheld)
        if skipped and name == "DXE.inc":
            header += ("#\n"
                       "#  Packaged under Binaries/gauguin/ but NOT in this file, so not in\n"
                       "#  the firmware volume. The reference has no line for them. Add an\n"
                       "#  INF line if any turns out to be needed:\n")
            header += "".join(f"#    {s}\n" for s in skipped)
        header += "##\n"
        out[key] = header + "\n".join(lines) + "\n"
        out[key + "_dropped"] = dropped
        if withheld:
            out.setdefault("apriori_extras_withheld", []).extend(
                (a, p) for a, p in withheld)
        out["orphans_seen"] = set(skipped)
        all_referenced.update(referenced)
        if moved:
            out["apriori_moved"] = moved
        if uhci:
            out.setdefault("xhci_host", []).extend(uhci)
        if xhci_dropped:
            out.setdefault("xhci_dropped", []).extend(xhci_dropped)
    out.pop("orphans_seen", None)
    out["referenced"] = all_referenced
    return out


def emit_raw_inc(raw_dir, guid_table, device):
    """Generate RAW.inc from the config and panel files we actually extracted.

    These are the FREEFORM files the firmware volume has to carry for Qualcomm's
    signed drivers to find their configuration: the UEFI PIL config, the charger
    and secure-partition configs, the boot menu, the boot logo, the battery
    indicator bitmaps, and the display panel descriptions.
    """
    names = sorted(f[:-4] for f in os.listdir(raw_dir) if f.endswith(".raw"))
    known, fresh = [], []
    for n in names:
        (known if n in guid_table else fresh).append(n)

    w = ["##",
         "#  GENERATED by tools/make_uefi_platform.py - do not edit by hand.",
         "#",
         f"#  {len(names)} FREEFORM files recovered from this device's XBL:",
         f"#    {len(known)} carry a GUID already used elsewhere in Mu-Silicium and are",
         "#       emitted with it, because Qualcomm's signed drivers look these files",
         "#       up by firmware-file GUID.",
         f"#    {len(fresh)} are not referenced by any existing platform package; their",
         "#       GUIDs are generated deterministically here. Nothing looks them up by",
         "#       GUID, so the value only has to be unique.",
         "##", ""]

    for n in names:
        if n in guid_table:
            guid, note = guid_table[n], ""
        else:
            guid, note = guid_for(n), "  # generated"
        w.append(f'  FILE FREEFORM = {guid} {{')
        w.append(f'    SECTION UI = "{n}"')
        w.append(f'    SECTION RAW = Binaries/{device}/RawFiles/{n}')
        w.append(f'  }}{note}')
        w.append("")
    return "\n".join(w).rstrip() + "\n"


def emit_devicebuild(ref_dir, device, packagename):
    """Produce DeviceBuild.py from the reference package.

    This file is almost entirely boilerplate that names the device: the
    platform DSC path, the package name, the build scope, PRODUCT_NAME. The
    reference and this board differ in nothing else, so rather than copy it by
    hand and let the two drift, it is derived.
    """
    src = os.path.join(ref_dir, "DeviceBuild.py")
    text = open(src, encoding="utf-8").read()
    text = text.replace(REF_PLATFORM, device).replace(REF_PLATFORM.capitalize(),
                                                      device.capitalize())
    header = (f"##\n"
              f"#  GENERATED by tools/make_uefi_platform.py from\n"
              f"#  {REF_PLATFORM}Pkg/DeviceBuild.py - do not edit by hand.\n"
              f"#\n"
              f"#  Differs from the reference only in the device name.\n"
              f"##\n")
    # The reference already opens with its own licence banner; keep it, but put
    # this note above so the file does not look hand-written.
    return header + text, text.count(f'"{device}')


def write_common(out_root, packagename, socinc, model):
    """Write the DSC/FDF/DEC/INC files a Mu-Silicium platform package needs."""
    pkg = os.path.join(out_root, "Platforms/Xiaomi", f"{packagename}Pkg")
    os.makedirs(os.path.join(pkg, "Include"), exist_ok=True)

    files = {
        f"{packagename}.dsc": model["dsc"],
        f"{packagename}.fdf": GAUGUIN_FDF,
        f"{packagename}.dec": GAUGUIN_DEC,
        "DeviceBuild.py": model["devicebuild"],
        "Include/DXE.inc": model["dxe_inc"],
        "Include/APRIORI.inc": model["apriori_inc"],
        "Include/RAW.inc": model["raw_inc"],
        "Library/MemoryMapLib/MemoryMapLib.inf": MEMMAP_INF,
        "Library/ConfigurationMapLib/ConfigurationMapLib.inf": CONFIGMAP_INF,
    }
    for name, text in files.items():
        path = os.path.join(pkg, name)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as fh:
            fh.write(text)
    return pkg


# ---------------------------------------------------------------------------
# The two libraries the platform DSC resolves at board level.
#
# The .c files for these are emitted by emit_memmap()/emit_configmap() above;
# these are only their INF wrappers. The FILE_GUIDs are the reference
# package's - an EDK2 library's GUID is an internal build identifier and
# nothing looks it up at runtime, so reusing surya's is both correct and one
# less invented value.
MEMMAP_INF = """[Defines]
  INF_VERSION                    = 0x00010005
  BASE_NAME                      = MemoryMapLib
  FILE_GUID                      = 375C4FF0-1905-4BA7-A5CA-7D40D25F5EF3
  MODULE_TYPE                    = BASE
  VERSION_STRING                 = 1.0
  LIBRARY_CLASS                  = MemoryMapLib

[Sources]
  MemoryMapLib.c

[Packages]
  ArmPkg/ArmPkg.dec
  MdePkg/MdePkg.dec
  SiliciumPkg/SiliciumPkg.dec
"""

CONFIGMAP_INF = """[Defines]
  INF_VERSION                    = 0x00010005
  BASE_NAME                      = ConfigurationMapLib
  FILE_GUID                      = D7DDE228-62E4-43E3-B5A1-AB29FB9B0A35
  MODULE_TYPE                    = BASE
  VERSION_STRING                 = 1.0
  LIBRARY_CLASS                  = ConfigurationMapLib

[Sources]
  ConfigurationMapLib.c

[Packages]
  MdePkg/MdePkg.dec
  QcomPkg/QcomPkg.dec
"""


# ---------------------------------------------------------------------------
# The SoC-level (BitraPkg) libraries.
#
# SEC runs before there is any driver model, so PlatformSecLib is what turns the
# watchdog off - without it the phone resets a few seconds into the firmware
# and never reaches the shell, which is a failure that looks like a bad image.
# ---------------------------------------------------------------------------

PLATFORMSEC_INF = """##
#  Bitra (SM7225) platform SEC library - generated for gauguin.
#  SPDX-License-Identifier: BSD-2-Clause-Patent
##

[Defines]
  INF_VERSION                    = 0x00010005
  BASE_NAME                      = PlatformSecLib
  FILE_GUID                      = 2C33C03B-D643-4792-8A90-EEF53A555C7D
  MODULE_TYPE                    = SEC
  VERSION_STRING                 = 1.0
  LIBRARY_CLASS                  = PlatformSecLib

[Sources]
  PlatformSec.c

[Sources.AArch64]
  AArch64/PlatformHelper.S

[Packages]
  ArmPkg/ArmPkg.dec
  MdePkg/MdePkg.dec
  SiliciumPkg/SiliciumPkg.dec
  QcomPkg/QcomPkg.dec

[LibraryClasses]
  IoLib
  MemoryMapHelperLib
  ArmSmmuDetachLib
"""

PLATFORMSEC_C = """/**
  Copyright (c) 2011-2012, ARM Limited. All rights reserved.
  SPDX-License-Identifier: BSD-2-Clause-Patent
**/

#include <Library/IoLib.h>
#include <Library/PlatformSecLib.h>
#include <Library/MemoryMapHelperLib.h>
#include <Library/ArmSmmuDetachLib.h>

#include "PlatformRegisters.h"

VOID
DisableWatchDogTimer ()
{
  EFI_STATUS                   Status;
  EFI_MEMORY_REGION_DESCRIPTOR WDogRegion;

  // Locate "APSS_WDT_TMR1" Memory Region
  Status = LocateMemoryRegionByName ("APSS_WDT_TMR1", &WDogRegion);
  if (EFI_ERROR (Status)) {
    return;
  }

  // Disable WatchDog Timer
  MmioWrite32 (WDogRegion.Address + APSS_WDT_ENABLE_OFFSET, 0x0);
}

VOID
PlatformInitialize ()
{
  // Disable WatchDog Timer
  DisableWatchDogTimer ();

  // Set MDP SIDs
  //
  // Only 0x800 is confirmed for this SoC: it is the SID the mainline SM6350
  // device tree gives the display subsystem. The rest of the list is inherited
  // from MooreaPkg (SM7150), which is the same generation of display block
  // (and whose 0x800 - 0xC41 range contains the one value we can confirm).
  // These are the rotation and VBIF stream IDs, which the device tree does not
  // describe because Linux's DRM driver attaches them itself.
  //
  // P5: confirm the full set against Qualcomm's own DisplayDxe before display
  // is brought up. Detaching a SID that is not in use is harmless, so the risk
  // here is a missing one, not an extra.
  CONST UINT16 MdpStreams[] = { 0x800, 0x801, 0x840, 0x841, 0xC00, 0xC01, 0xC40, 0xC41 };

  // Detach IOMMU Domains
  ArmSmmuDetach (MdpStreams, ARRAY_SIZE (MdpStreams));
}
"""

PLATFORMREGISTERS_H = """#ifndef _PLATFORM_REGISTERS_H_
#define _PLATFORM_REGISTERS_H_

//
// SMMU Bank Details
//
#define SMMU_CTX_BANK_SIZE                     0x1000

//
// SMMU Bank Offsets
//
#define SMMU_CTX_BANK_0_OFFSET                 0x80000

//
// SMMU Bank Register Offsets
//
#define SMMU_CTX_BANK_SCTLR_OFFSET             0x00
#define SMMU_CTX_BANK_TTBR0_0_OFFSET           0x20
#define SMMU_CTX_BANK_TTBR0_1_OFFSET           0x24
#define SMMU_CTX_BANK_TTBR1_0_OFFSET           0x28
#define SMMU_CTX_BANK_TTBR1_1_OFFSET           0x2C
#define SMMU_CTX_BANK_MAIR0_OFFSET             0x38
#define SMMU_CTX_BANK_MAIR1_OFFSET             0x3C
#define SMMU_CTX_BANK_TTBCR_OFFSET             0x30

//
// SMMU SCTLR
//
#define SMMU_CCA_SCTLR                         0x9F00E0

//
// SMMU Context Banks
//
#define UFS_CTX_BANK                           2

//
// WatchDog Timer Registers
//
// Verified against mainline: sm6350.dtsi declares the watchdog as
// "qcom,apss-wdt-sm6350", "qcom,kpss-wdt", and drivers/watchdog/qcom-wdt.c
// matches on the *second* compatible -> match_data_kpss -> WDT_EN = 0x8.
// (The other layout in that driver, match_data_apcs_tmr, puts it at 0x40 and
// is for the older "qcom,kpss-timer".)
//
#define APSS_WDT_ENABLE_OFFSET                 0x8

#endif /* _PLATFORM_REGISTERS_H_ */
"""

PLATFORMHELPER_S = """//
// Copyright (c) 2012-2013, ARM Limited. All rights reserved.
// SPDX-License-Identifier: BSD-2-Clause-Patent
//

#include <AsmMacroLib.h>

ASM_FUNC (PlatformAssemblyInitialize)
  // Nothing to do Here.
  ret
"""

ACPI_UPDATE_INF = """##
#  Bitra (SM7225) ACPI table update library - generated for gauguin.
#  SPDX-License-Identifier: BSD-2-Clause-Patent
##

[Defines]
  INF_VERSION                    = 0x00010005
  BASE_NAME                      = AcpiTableUpdateLib
  FILE_GUID                      = 2FDF4E63-5AD5-4385-A729-868019B45A99
  MODULE_TYPE                    = DXE_DRIVER
  VERSION_STRING                 = 1.0
  LIBRARY_CLASS                  = AcpiTableUpdateLib|DXE_DRIVER

[Sources]
  AcpiTableUpdate.c

[Packages]
  ArmPkg/ArmPkg.dec
  MdePkg/MdePkg.dec
  QcomPkg/QcomPkg.dec
  SiliciumPkg/SiliciumPkg.dec
"""

ACPI_UPDATE_C = """/**
  Bitra (SM7225) ACPI table update library.

  SPDX-License-Identifier: BSD-2-Clause-Patent
**/

#include <Library/AcpiTableUpdateLib.h>

/**
  Patch board-specific values into the DSDT before it is handed to the OS.

  P3: this is a deliberate no-op. The sibling SoC packages fill in the modem,
  ADSP and TZ shared-memory regions by reading them from SMEM and writing them
  into named DSDT fields, and they do it against a DSDT that was written for
  their board. There is no DSDT for gauguin yet, so there are no fields to
  write to - and inventing values with no table to put them in would only
  produce a build that looks finished and an OS that boots to a stop code.

  When P3 adds the ACPI tables, this is where the SMEM-derived regions go.
**/
VOID
UpdateAcpiTables ()
{
  return;
}
"""


def emit_acpi_tables(out_root):
    """Write the platform's ACPI table package under Silicium-ACPI/.

    The DSDT is the one table this port authors; its source lives in
    tools/acpi/gauguin.asl and is copied here so the tree carrying the .inf
    also carries the thing the .inf is built from. The compiled DSDT.aml is
    not written here - tools/sync-uefi-platform.sh runs iasl over the copy -
    so that a checked-in tree never disagrees with its own source.
    """
    d = os.path.join(out_root, "Silicium-ACPI/Platforms/Xiaomi/gauguin")
    os.makedirs(d, exist_ok=True)

    src = os.path.join(REPO, "tools/acpi/gauguin.asl")
    if not os.path.isfile(src):
        sys.exit(f"missing {src} - the DSDT source is the one hand-written "
                 f"file this generator installs")
    with open(src, encoding="utf-8") as fh:
        asl = fh.read()

    with open(os.path.join(d, "AcpiTables.inf"), "w") as fh:
        fh.write(GAUGUIN_ACPI_INF)
    with open(os.path.join(d, "gauguin.asl"), "w") as fh:
        fh.write(asl)
    return d


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", default=REPO)
    ap.add_argument("--out", default=None,
                    help="where to write the packages (default: <repo>/uefi)")
    ap.add_argument("--dxe-dir", default=None,
                    help="extracted DXE drivers (default: <repo>/device/dxe)")
    ap.add_argument("--mu", default=None,
                    help="Mu-Silicium checkout (default: <repo>/work/uefi/Mu-Silicium)")
    #
    # The default is `simple`, not `qcom`, because a default is what a plain
    # regeneration produces and that has to be the configuration that has been
    # on the device. DisplayDxe re-initialises the panel from the panel XML and
    # its failure mode is a black screen, which on a phone with no UART is
    # indistinguishable from a firmware that never ran; SimpleFbDxe draws onto
    # the framebuffer the bootloader has just painted and has put text on this
    # panel for every measurement in docs/08. Flipping to `qcom` is a bring-up
    # step of its own, taken once DXE reaches BDS - not something that should
    # happen by omitting a flag.
    #
    ap.add_argument("--display", choices=("qcom", "simple"), default="simple",
                    help="qcom = Qualcomm DisplayDxe (the goal, untested on this "
                         "panel); simple = SiliciumPkg SimpleFbDxe (draws on the "
                         "bootloader's framebuffer, no panel bring-up). "
                         "Default: simple")
    ap.add_argument("--xhci-host", action="store_true",
                    help="add the USB host stack (XhciPciEmulationDxe, XhciDxe, "
                         "UsbInitDxe) behind USE_XHCI_HOST_DRIVER=1. Needed for a "
                         "USB stick to be visible; the blobs come from "
                         "Binaries/bitra/, the SM7225 sibling, because this "
                         "device's XBL has no host driver to extract. "
                         "Default: off")
    ap.add_argument("--apriori-extras", action="store_true",
                    help="promote the four EXTRA_DRIVERS of APRIORI.inc "
                         "(PwrUtilsDxe, VcsDxe, FeatureEnablerDxe, MacDxe) into "
                         "the a-priori batch at their alioth anchors. The stock "
                         "firmware's own array promotes three of the four, so "
                         "this is what the phone shipped; it is off by default "
                         "because promotion disables the promoted driver's depex "
                         "(`Dispatcher.c:2111` sets Dependent = FALSE) and that "
                         "is a device-visible change nothing has measured yet")
    ap.add_argument("--apriori-move", action="append", default=[],
                    metavar="ANCHOR:NAME[,NAME...]",
                    help="move the named APRIORI.inc INF lines to just after "
                         "ANCHOR, keeping the order they are named in. Repeatable "
                         "(later moves see the result of earlier ones). Changes "
                         "the order the a-priori batch runs in and nothing else - "
                         "see the note at REF_PLATFORM. Off by default, so a "
                         "plain run reproduces the reference order exactly.")
    args = ap.parse_args()

    apriori_moves = []
    for spec in args.apriori_move:
        anchor, _, names = spec.partition(":")
        if not anchor or not names:
            ap.error(f"--apriori-move wants ANCHOR:NAME[,NAME...], got {spec!r}")
        apriori_moves.append((anchor, [n for n in names.split(",") if n]))

    cfg = os.path.join(args.repo, "device/config/uefiplat.cfg")
    if not os.path.isfile(cfg):
        sys.exit(f"missing {cfg}")
    out_root = args.out or os.path.join(args.repo, "uefi")
    dxe_dir = args.dxe_dir or os.path.join(args.repo, "device/dxe")
    mu_root = args.mu or os.path.join(args.repo, "work/uefi/Mu-Silicium")

    memory, registers, params = parse_uefiplat(cfg)
    print(f"uefiplat.cfg: {len(memory)} DDR regions, {len(registers)} register "
          f"regions, {len(params)} config parameters")

    soc = os.path.join(out_root, "Silicon/Qualcomm/BitraPkg")
    board = os.path.join(out_root, "Platforms/Xiaomi/gauguinPkg")
    for d in (os.path.join(soc, "Library/MemoryMapLib"),
              os.path.join(soc, "Library/PlatformSecLib"),
              os.path.join(soc, "Library/AcpiTableUpdateLib"),
              os.path.join(board, "Library/MemoryMapLib"),
              os.path.join(board, "Library/ConfigurationMapLib"),
              os.path.join(board, "Include"),
              os.path.join(out_root, "Binaries/gauguin/RawFiles"),
              os.path.join(out_root, "Resources/Configs")):
        os.makedirs(d, exist_ok=True)

    with open(os.path.join(soc, "BitraPkg.dsc.inc"), "w") as fh:
        fh.write(BITRA_DSC_INC.format(**SOC_DEFAULTS))
    print("wrote BitraPkg.dsc.inc")

    soclib = {
        "Library/PlatformSecLib/PlatformSecLib.inf": PLATFORMSEC_INF,
        "Library/PlatformSecLib/PlatformSec.c": PLATFORMSEC_C,
        "Library/PlatformSecLib/PlatformRegisters.h": PLATFORMREGISTERS_H,
        "Library/PlatformSecLib/AArch64/PlatformHelper.S": PLATFORMHELPER_S,
        "Library/AcpiTableUpdateLib/AcpiTableUpdateLib.inf": ACPI_UPDATE_INF,
        "Library/AcpiTableUpdateLib/AcpiTableUpdate.c": ACPI_UPDATE_C,
    }
    for name, text in soclib.items():
        path = os.path.join(soc, name)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as fh:
            fh.write(text)
    print(f"wrote {len(soclib)} BitraPkg library source files")

    with open(os.path.join(board, "Library/MemoryMapLib/MemoryMapLib.c"), "w") as fh:
        n = emit_memmap(memory, registers, fh)
    print(f"wrote MemoryMapLib.c ({n} regions)")

    with open(os.path.join(board, "Library/ConfigurationMapLib/ConfigurationMapLib.c"), "w") as fh:
        n = emit_configmap(params, fh)
    print(f"wrote ConfigurationMapLib.c ({n} entries)")

    # The driver lists come from the reference package, filtered to the blobs we
    # actually extracted. Checked rather than assumed: an INF without a matching
    # .efi is a build failure, and a driver we lack is a hole in the firmware.
    if not os.path.isdir(dxe_dir):
        sys.exit(f"missing {dxe_dir} - run tools/xbl_extract.py first")
    have = present_drivers(dxe_dir)

    # The USB host stack is the one part of the firmware whose blobs cannot come
    # from this device, so it is staged from the SM7225 sibling and only then
    # becomes something the generated lists are allowed to reference.
    if args.xhci_host:
        print(f"USB host stack: staging from Binaries/{SIBLING_SOURCE}")
        have |= stage_sibling_blobs(
            mu_root, os.path.join(out_root, "Binaries", "gauguin"),
            sorted(SIBLING_BLOBS))

    ref_dir = os.path.join(mu_root, "Platforms/Xiaomi", f"{REF_PLATFORM}Pkg")
    if not os.path.isdir(ref_dir):
        sys.exit(f"missing reference package {ref_dir}\n"
                 f"clone Mu-Silicium into {mu_root} first")
    model = rewrite_incs(ref_dir, have, "gauguin", apriori_moves,
                         xhci_host=args.xhci_host,
                         apriori_extras=args.apriori_extras)
    for anchor, path in model.pop("apriori_moved", []):
        print(f"  a-priori move: {path}")
        print(f"                 -> after {anchor}")
    for note in model.pop("xhci_dropped", []):
        print(f"  USB host stack, NOT inserted: {note}")
    for anchor, path in model.pop("apriori_extras_withheld", []):
        print(f"  a-priori promotion withheld: {path}")
        print(f"                               would go after {anchor}")
        print(f"                               (--apriori-extras to insert it)")
    xhci = model.pop("xhci_host", [])
    if xhci:
        print(f"USB host stack: {len(xhci)} INF line(s) in "
              f"!if $({XHCI_HOST_GUARD}) == 1")

    guid_table = load_guid_table(mu_root)
    model["raw_inc"] = emit_raw_inc(dxe_dir, guid_table, "gauguin")
    model["dsc"] = GAUGUIN_DSC.format(display=1 if args.display == "qcom" else 0,
                                      xhci_host=1 if args.xhci_host else 0)
    print(f"display driver: "
          f"{'Qualcomm DisplayDxe' if args.display == 'qcom' else 'SimpleFbDxe'}")
    model["devicebuild"], ndev = emit_devicebuild(ref_dir, "gauguin", "gauguinPkg")
    print(f"wrote DXE.inc / APRIORI.inc ({len(have)} drivers), "
          f"RAW.inc ({len(glob.glob(os.path.join(dxe_dir, '*.raw')))} files, "
          f"{len(guid_table)} GUIDs on file), "
          f"DeviceBuild.py ({ndev} device-name substitutions)")

    # Blobs we have but the reference lists never mention. Not a failure - the
    # reference is a different board - but each one is a driver that would be
    # silently left out of the firmware, so they are named rather than buried.
    orphans = sorted(have - model.pop("referenced"))
    if orphans:
        print(f"  {len(orphans)} blobs are packaged but not listed by the "
              f"{REF_PLATFORM} reference:")
        for o in orphans:
            print(f"    {o}")

    pkg = write_common(out_root, "gauguin", "BitraPkg/BitraPkg.dsc.inc", model)
    print(f"wrote platform package {pkg}")

    toml = os.path.join(out_root, "Resources/Configs/gauguin.toml")
    with open(toml, "w") as fh:
        fh.write(GAUGUIN_TOML)
    print(f"wrote {os.path.relpath(toml, out_root)}")

    acpi = emit_acpi_tables(out_root)
    print(f"wrote ACPI table package {os.path.relpath(acpi, out_root)} "
          f"(AcpiTables.inf + gauguin.asl)")

    print(f"\npackages written under {out_root}")
    print("next: tools/sync-uefi-platform.sh to install them into the Mu-Silicium tree")


if __name__ == "__main__":
    main()
