#!/usr/bin/env bash
#
# Install the generated gauguin UEFI platform into a Mu-Silicium checkout.
#
# The packages under `uefi/` are generated by tools/make_uefi_platform.py and
# tools/make_xbl_binaries.py; nothing here is hand-written. This script only
# puts them where Mu-Silicium's build expects to find them, compiling the DTB
# on the way, and then optionally builds.
#
# Mu-Silicium builds the *whole* firmware from a checkout that also carries 40
# other devices' packages. Everything this script installs is inside a path
# named gauguin, so a sync is additive and a re-sync overwrites only our own
# files - with two exceptions, both noted below: the DTB directory is shared,
# and Mu_Basecore is patched rather than overwritten.
#
# Usage:  sync-uefi-platform.sh [--mu DIR] [--build] [--clean]

set -euo pipefail

REPO=$(cd "$(dirname "$0")/.." && pwd)
MU=${MU:-$REPO/work/uefi/Mu-Silicium}
GEN=$REPO/uefi
BUILD=0

while [ $# -gt 0 ]; do
    case "$1" in
        --mu)     MU=$2; shift 2 ;;
        --clean)  CLEAN=--clean; shift ;;
        --build)  BUILD=1; shift ;;
        -h|--help) sed -n '2,20p' "$0"; exit 0 ;;
        *) echo "unknown option: $1" >&2; exit 1 ;;
    esac
done

die() { echo "error: $*" >&2; exit 1; }
say() { printf '\033[1m== %s\033[0m\n' "$*"; }

[ -d "$MU" ] || die "no Mu-Silicium checkout at $MU (use --mu)"
[ -d "$GEN" ] || die "no generated packages at $GEN - run tools/make_uefi_platform.py"
[ -f "$MU/build_uefi.py" ] || die "$MU does not look like a Mu-Silicium checkout"

# The generator is the source of truth; refuse to sync a stale tree rather than
# silently building something that does not match the device data.
need=(
    "$GEN/Platforms/Xiaomi/gauguinPkg/gauguin.dsc"
    "$GEN/Platforms/Xiaomi/gauguinPkg/gauguin.fdf"
    "$GEN/Platforms/Xiaomi/gauguinPkg/DeviceBuild.py"
    "$GEN/Platforms/Xiaomi/gauguinPkg/Include/DXE.inc"
    "$GEN/Platforms/Xiaomi/gauguinPkg/Include/APRIORI.inc"
    "$GEN/Platforms/Xiaomi/gauguinPkg/Include/RAW.inc"
    "$GEN/Silicon/Qualcomm/BitraPkg/BitraPkg.dsc.inc"
    "$GEN/Resources/Configs/gauguin.toml"
)
for f in "${need[@]}"; do
    [ -f "$f" ] || die "missing $f - re-run tools/make_uefi_platform.py"
done

# ---------------------------------------------------------------------------
# The host stack is the one part of the driver list that comes from a *flag*
# rather than from the device, and a regeneration that forgets the flag looks
# like a healthy tree to every check above. `--xhci-host` sets
# `USE_XHCI_HOST_DRIVER = 1` and the three INF lines behind it, and it is what
# stages three blobs this phone's XBL does not carry at all - XhciPciEmulationDxe,
# XhciDxe and UsbInitDxe, taken from the SM7225 sibling (SIBLING_BLOBS in
# tools/make_xbl_binaries.py). Staging is additive and idempotent: it overwrites
# the three directories it owns and touches nothing else, so a later run
# *without* the flag does not take them away again. That is the state worth
# guarding, and it is the one this script used to install without a word - a
# tree carrying the three blob directories and no INF line for any of them,
# whose DSC variable has gone back to 0. The payload that costs is the one built
# without the thing the host stack exists to test, and nothing else here would
# have noticed, because the missing INFs leave no hole: the volume simply has
# three fewer drivers. So the two halves are checked against each other rather
# than against the flag. A staged blob with no INF line is a driver packaged
# nowhere; an INF line with no blob is a build failure minutes later with the
# table list as the only clue. A tree that never had the flag has neither half
# and passes, which is correct - it is a coherent tree, just not this one.
HOST_STACK=(XhciPciEmulationDxe XhciDxe UsbInitDxe)
host_in_volume=0
for d in "${HOST_STACK[@]}"; do
    inf="Binaries/gauguin/QcomPkg/Drivers/$d/$d.inf"
    listed=no
    grep -q "^  INF $inf\$" "$GEN/Platforms/Xiaomi/gauguinPkg/Include/DXE.inc" && listed=yes
    staged=no
    [ -d "$GEN/Binaries/gauguin/QcomPkg/Drivers/$d" ] && staged=yes
    if [ "$staged$listed" = yesyes ]; then
        host_in_volume=$((host_in_volume + 1))
    elif [ "$staged$listed" = yesno ]; then
        die "$d is staged under Binaries/gauguin but DXE.inc carries no INF line for it - this tree was generated without --xhci-host over one that had it, so the blob would ship in no volume"
    elif [ "$staged$listed" = noyes ]; then
        die "DXE.inc names $inf but no such blob is staged under Binaries/gauguin - the build would fail on a missing file"
    fi
done
echo "   host stack  ($host_in_volume of 3 drivers, USE_XHCI_HOST_DRIVER = $(sed -n 's/^ *USE_XHCI_HOST_DRIVER *= *//p' "$GEN/Platforms/Xiaomi/gauguinPkg/gauguin.dsc"))"

# ---------------------------------------------------------------------------
say "installing platform package"
# ---------------------------------------------------------------------------
install -d "$MU/Platforms/Xiaomi/gauguinPkg"
cp -a "$GEN/Platforms/Xiaomi/gauguinPkg/." "$MU/Platforms/Xiaomi/gauguinPkg/"
echo "   Platforms/Xiaomi/gauguinPkg  ($(find "$GEN/Platforms/Xiaomi/gauguinPkg" -type f | wc -l) files)"

# ---------------------------------------------------------------------------
say "installing SoC package"
# ---------------------------------------------------------------------------
# BitraPkg is the SM7225 layer. Mu-Silicium has no BitraPkg, and the name does
# not collide with anything in Silicon/Qualcomm, so this is a clean addition.
install -d "$MU/Silicon/Qualcomm/BitraPkg"
cp -a "$GEN/Silicon/Qualcomm/BitraPkg/." "$MU/Silicon/Qualcomm/BitraPkg/"
echo "   Silicon/Qualcomm/BitraPkg"

# ---------------------------------------------------------------------------
say "installing device binaries"
# ---------------------------------------------------------------------------
# 55 signed Qualcomm DXE drivers + 32 config/panel files, all extracted from
# this phone's own XBL. These are Qualcomm's signed images and they ship as they
# came out of the extraction: the INF beside each one is written by
# tools/make_xbl_binaries.py, but nothing in this project rewrites a PE. The
# GUID_NAMESPACE note in that file says why even the INF's own GUID is generated
# rather than reproduced from Qualcomm's.
#
# Three more directories sit beside them that this phone's XBL does not carry
# at all: XhciPciEmulationDxe, XhciDxe and UsbInitDxe, staged from the SM7225
# sibling's Binaries/bitra/ because there is no host-controller driver in this
# device to extract. Only the generator's `--xhci-host` stages them, and nothing
# removes them again - so their presence here says a flag was used once, not
# that the tree being installed is the one that used it. The check above is what
# tells those two apart. See SIBLING_BLOBS in tools/make_xbl_binaries.py.
install -d "$MU/Binaries/gauguin"
cp -a "$GEN/Binaries/gauguin/." "$MU/Binaries/gauguin/"
echo "   Binaries/gauguin  ($(find "$GEN/Binaries/gauguin" -type f | wc -l) files)"

# ---------------------------------------------------------------------------
say "installing device config"
# ---------------------------------------------------------------------------
install -d "$MU/Resources/Configs"
cp "$GEN/Resources/Configs/gauguin.toml" "$MU/Resources/Configs/gauguin.toml"
echo "   Resources/Configs/gauguin.toml"

# ---------------------------------------------------------------------------
say "installing ACPI tables"
# ---------------------------------------------------------------------------
# Silicium-ACPI is a submodule of the Mu-Silicium checkout, so the platform's
# table package cannot live in it - it is copied in from the generated tree on
# every sync. DSDT.aml is compiled here from the .asl beside it rather than
# committed, so a tree can never carry a binary that disagrees with its source.
ACPI_SRC=$GEN/Silicium-ACPI/Platforms/Xiaomi/gauguin
ACPI_DST=$MU/Silicium-ACPI/Platforms/Xiaomi/gauguin
[ -f "$ACPI_SRC/AcpiTables.inf" ] || die "missing $ACPI_SRC/AcpiTables.inf - re-run tools/make_uefi_platform.py"
[ -f "$ACPI_SRC/gauguin.asl" ] || die "missing $ACPI_SRC/gauguin.asl"
# The generated tree is an intermediate, and an edit to tools/acpi/gauguin.asl
# does not reach it on its own. A stale one still has a plausible AcpiTables.inf
# beside it, so the checks below would pass and this script would install the
# previous DSDT while printing a new-looking line - which is exactly what it did
# once, silently costing a build. Catch it here, the same way a missing .inf is
# caught, rather than trusting the size in the line below.
if ! cmp -s "$REPO/tools/acpi/gauguin.asl" "$ACPI_SRC/gauguin.asl"; then
    die "$ACPI_SRC/gauguin.asl is stale (differs from tools/acpi/gauguin.asl) - re-run tools/make_uefi_platform.py"
fi
command -v iasl >/dev/null 2>&1 || die "iasl not found - install acpica-tools"

install -d "$ACPI_DST"
cp "$ACPI_SRC/AcpiTables.inf" "$ACPI_DST/AcpiTables.inf"
cp "$ACPI_SRC/gauguin.asl" "$ACPI_DST/gauguin.asl"
if ! iasl -p "$ACPI_DST/DSDT" "$ACPI_DST/gauguin.asl" >/tmp/iasl-gauguin.log 2>&1 ||
   ! grep -q "0 Errors" /tmp/iasl-gauguin.log; then
    sed 's/^/     /' /tmp/iasl-gauguin.log | tail -20
    die "iasl failed on gauguin.asl"
fi
echo "   Silicium-ACPI/Platforms/Xiaomi/gauguin  (DSDT.aml $(stat -c%s "$ACPI_DST/DSDT.aml") bytes, from gauguin.asl)"

# EDK2 resolves each [Binaries] ASL path against the module's own directory
# first and then against each PackagesPath entry, and a miss is a build failure
# minutes later with the table list as the only clue - so it is checked here
# instead. The three roots are the Silicium-ACPI entries gauguin's
# DeviceBuild.py puts on PackagesPath, in the order it puts them there: the
# package's own directory is where DSDT.aml lands, `Common/SSDT.aml` sits at
# the Silicium-ACPI root, and `Moorea/*.aml` under Silicon/Qualcomm.
for t in $(sed -n 's/^  ASL|//p' "$ACPI_DST/AcpiTables.inf"); do
    found=
    for root in "$ACPI_DST" "$MU/Silicium-ACPI" "$MU/Silicium-ACPI/Silicon/Qualcomm"; do
        [ -f "$root/$t" ] && { found=$root/$t; break; }
    done
    [ -n "$found" ] || die "AcpiTables.inf names $t but no PackagesPath root under Silicium-ACPI provides it"
done
echo "   all $(sed -n 's/^  ASL|//p' "$ACPI_DST/AcpiTables.inf" | wc -l) named tables resolve"

# ---------------------------------------------------------------------------
say "applying local edits to Mu_Basecore"
# ---------------------------------------------------------------------------
# Mu_Basecore is a nested checkout of upstream microsoft/mu_basecore, and it
# lives under work/, which this repository ignores - so the edits that make the
# firmware build and behave on this device are carried as a patch instead of as
# a commit in someone else's repository. Without this step a fresh checkout
# builds a firmware that was never tested on the device. The patch's own header
# lists what is in it and how to regenerate it after editing the checkout.
#
# Idempotent: the tree already carrying the patch fails the forward check and
# passes the reverse one, which is the second branch.
PATCH=$REPO/uefi/patches/mu-basecore-local.patch
[ -f "$PATCH" ] || die "missing $PATCH"
BASECORE=$MU/Mu_Basecore
# `.git` is a file here, not a directory: Mu_Basecore is a submodule of the
# Mu-Silicium checkout, so its git dir lives in ../.git/modules/Mu_Basecore.
git -C "$BASECORE" rev-parse --git-dir >/dev/null 2>&1 || die "$BASECORE is not a git checkout"
if git -C "$BASECORE" apply --check "$PATCH" 2>/dev/null; then
    git -C "$BASECORE" apply "$PATCH"
    echo "   applied  (tree was pristine)"
elif git -C "$BASECORE" apply --reverse --check "$PATCH" 2>/dev/null; then
    echo "   already applied"
else
    die "cannot apply $PATCH to $BASECORE - the tree has diverged, reconcile it by hand"
fi

# ---------------------------------------------------------------------------
say "building the device tree"
# ---------------------------------------------------------------------------
DTS=$REPO/dts/sm7225-xiaomi-gauguin.dts
PREBUILT=$REPO/work/out/sm7225-xiaomi-gauguin.dtb
KERNEL=$REPO/work/linux
[ -f "$DTS" ] || die "missing $DTS"

install -d "$MU/Resources/DTBs"

# build_uefi.py appends Resources/DTBs/<device>.dtb to the UEFI image, and the
# Android bootloader validates that DTB's qcom,msm-id before it will accept the
# image at all - which is why this has to be OUR device tree and not a
# placeholder. The board file uses #include and #define, so it needs the C
# preprocessor first; the kernel build already does exactly this, so its output
# is preferred over re-deriving it here.
if [ -f "$PREBUILT" ] && [ "$KERNEL/arch/arm64/boot/dts/qcom/sm6350.dtsi" -nt "$PREBUILT" ]; then
    echo "   note: the DTS is newer than the built DTB - re-run tools/build-kernel.sh"
fi

if [ -f "$PREBUILT" ]; then
    cp "$PREBUILT" "$MU/Resources/DTBs/gauguin.dtb"
    echo "   Resources/DTBs/gauguin.dtb  ($(stat -c%s "$MU/Resources/DTBs/gauguin.dtb") bytes, from the kernel build)"
elif [ -f "$KERNEL/arch/arm64/boot/dts/qcom/sm6350.dtsi" ]; then
    if cpp -nostdinc -undef -x assembler-with-cpp \
           -I "$KERNEL/arch/arm64/boot/dts/qcom" -I "$KERNEL/include" \
           "$DTS" /tmp/gauguin.dts.pp 2>/tmp/cpp-gauguin.log &&
       dtc -I dts -O dtb -o "$MU/Resources/DTBs/gauguin.dtb" /tmp/gauguin.dts.pp 2>/tmp/dtc-gauguin.log; then
        echo "   Resources/DTBs/gauguin.dtb  ($(stat -c%s "$MU/Resources/DTBs/gauguin.dtb") bytes, preprocessed locally)"
    else
        sed 's/^/     /' /tmp/cpp-gauguin.log /tmp/dtc-gauguin.log 2>/dev/null | head -20
        die "could not build the device tree"
    fi
else
    die "no device tree available: neither $PREBUILT nor a kernel tree at $KERNEL"
fi

# A parity copy, decompiled, so the DTB that ships can be read back and
# compared against the source without a separate tool. The reference packages
# keep both files; only the .dtb is used by the build.
dtc -I dtb -O dts -o "$MU/Resources/DTBs/gauguin.dts" "$MU/Resources/DTBs/gauguin.dtb" 2>/dev/null &&
    echo "   Resources/DTBs/gauguin.dts  (decompiled for review)"

# ---------------------------------------------------------------------------
if [ "$BUILD" = 0 ]; then
    say "installed. Build with:"
    echo "   cd $MU && source setup_env.sh -p apt && python3 build_uefi.py -d gauguin -r DEBUG ${CLEAN:-}"
    exit 0
fi

# ---------------------------------------------------------------------------
say "building"
# ---------------------------------------------------------------------------
cd "$MU"
# shellcheck disable=SC1091
source ./setup_env.sh -p apt >/dev/null 2>&1 || die "setup_env.sh failed"
python3 build_uefi.py -d gauguin -r DEBUG ${CLEAN:-}

say "output"
ls -l "$MU"/Mu-gauguin*.img "$MU"/Mu-gauguin*.bin 2>/dev/null || \
    echo "   no image produced - build log above"
